from flask import Flask, request, jsonify
from flask_cors import CORS
import os
import PyPDF2
from dotenv import load_dotenv
import uuid
import re

# LangChain imports
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains import LLMChain

load_dotenv()

app = Flask(__name__)
CORS(app, resources={r"/api/*": {"origins": "*"}})

# Initialize Gemini model via LangChain
gemini_api_key = os.getenv("GEMINI_API_KEY")
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=gemini_api_key,
    temperature=0.7,
)

# Storage for PDFs (in-memory)
os.makedirs("temp_uploads", exist_ok=True)
pdf_storage = {}


@app.route("/api/chat", methods=["POST"])
def chat():
    """Process a chat message using LangChain Gemini."""
    data = request.json
    user_message = data.get("message", "")
    settings = data.get("settings", {})
    pdf_ids = data.get("pdfIds", [])

    context = ""
    for pdf_id in pdf_ids:
        if pdf_id in pdf_storage:
            context += f"\nDocument: {pdf_storage[pdf_id]['name']}\n{pdf_storage[pdf_id]['content']}\n"

    response = get_langchain_response(user_message, context, settings)
    return jsonify(response)


@app.route("/api/upload", methods=["POST"])
def upload_pdf():
    """Handle PDF uploads."""
    if "file" not in request.files:
        return jsonify({"error": "No file part"}), 400

    file = request.files["file"]

    if file.filename == "":
        return jsonify({"error": "No selected file"}), 400

    if not file.filename.endswith(".pdf"):
        return jsonify({"error": "File must be a PDF"}), 400

    try:
        filename = file.filename
        file_path = os.path.join("temp_uploads", filename)
        file.save(file_path)

        pdf_text = extract_text_from_pdf(file_path)
        pdf_id = f"pdf-{uuid.uuid4().hex[:8]}"

        pdf_storage[pdf_id] = {
            "name": filename,
            "content": pdf_text,
            "size": os.path.getsize(file_path),
            "lastModified": os.path.getmtime(file_path),
        }

        return jsonify({
            "id": pdf_id,
            "name": filename,
            "size": os.path.getsize(file_path),
            "lastModified": os.path.getmtime(file_path),
        })
    except Exception as e:
        return jsonify({"error": f"Error processing PDF: {str(e)}"}), 500


@app.route("/api/export", methods=["POST"])
def export_conversation():
    """Acknowledge export request."""
    return jsonify({"success": True, "message": "Export successful"})


def get_langchain_response(question, context, settings):
    """Generate a response using LangChain + Gemini."""
    response_id = f"ai-{uuid.uuid4().hex[:8]}"

    # System instruction
    system_instruction = (
        "You are a helpful study assistant that provides accurate educational responses."
    )
    if settings.get("simplifiedAnswers"):
        system_instruction += " Provide simplified explanations for beginners."
    if settings.get("stepByStepSolutions"):
        system_instruction += " Include step-by-step reasoning where helpful."

    # Build prompt template
    prompt = ChatPromptTemplate.from_template(
        """{system_instruction}

Context (from PDFs or notes):
{context}

Question:
{question}

Respond clearly and accurately."""
    )

    chain = LLMChain(llm=llm, prompt=prompt)

    try:
        result = chain.run({
            "system_instruction": system_instruction,
            "context": context,
            "question": question,
        })

        response = {
            "id": response_id,
            "type": "ai",
            "content": result.strip(),
            "timestamp": "",
        }

        # Optional: Extract steps for UI display
        if settings.get("stepByStepSolutions"):
            steps = extract_steps_from_content(result)
            if steps:
                response["steps"] = steps

        if settings.get("showSources"):
            response["sources"] = [
                {"title": "Uploaded PDFs", "description": "Context from uploaded study materials"},
                {"title": "Generated by Gemini (via LangChain)", "url": "https://ai.google.dev/"},
            ]

        return response
    except Exception as e:
        return {
            "id": response_id,
            "type": "ai",
            "content": f"Error while generating response: {str(e)}",
            "timestamp": "",
        }


def extract_steps_from_content(content):
    """Extract stepwise information from text."""
    lines = content.split("\n")
    steps = []
    for line in lines:
        if re.match(r"^\d+[\.\)]", line.strip()) or line.strip().startswith("Step "):
            clean = re.sub(r"^\d+[\.\)]|^Step \d+[:\.]", "", line).strip()
            if clean:
                steps.append(clean)
    return steps[:5] if steps else None


def extract_text_from_pdf(file_path):
    """Extract text from a PDF file."""
    text = ""
    try:
        with open(file_path, "rb") as f:
            reader = PyPDF2.PdfReader(f)
            for page in reader.pages:
                text += page.extract_text() + "\n"
        return text.strip()
    except Exception as e:
        print(f"Error reading PDF: {e}")
        return ""


if __name__ == "__main__":
    print("Running Flask backend with LangChain integration...")
    app.run(debug=True, host="0.0.0.0", port=5000)
